from __future__ import annotations

from dataclasses import dataclass, field

from channel.ssh import HostSpec


@dataclass(slots=True)
class FaultStep:
    """Scenario-described step; contains what to run, not how to run."""

    host: HostSpec
    inject_command: str
    rollback_command: str
    parameters: dict[str, object] = field(default_factory=dict)


@dataclass(slots=True)
class ActionResult:
    """Execution result generated by agents."""

    host: str
    inject_command: str
    rollback_command: str
    success: bool


@dataclass(slots=True)
class OrchestratorSession:
    session_id: str
    scenario: str
    step_count: int = 0
    reports: list[ActionResult] = field(default_factory=list)

    def record(self, report: ActionResult) -> None:
        self.reports.append(report)
